name: cicd-journald

on:
  workflow_dispatch:
    inputs:
      servers:
        description: String array of servers to target (e.g., "server1,server2", defaults to "all")
        required: true
        type: string

jobs:
  output_servers:
    runs-on: ubuntu-latest
    env:
      servers: ${{ github.event.inputs.servers }}
    steps:
      - name: Output servers input
        run: |
          echo "servers=$servers"
